server {
    listen 80;
    server_name 150.158.51.199;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    location / {
        root /var/www/huntlink/frontend-web/dist;
        index index.html;
        try_files $uri $uri/ /index.html;

        # 解决乱码与缓存
        add_header Content-Type text/html;
        charset utf-8;
    }

    location /static/ {
        root /var/www/huntlink/frontend-web/dist;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location /api {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
